### ISSUE TITLE
FlyoutNavigationController is not a UINavigationController

### ISSUE THREAD

**Issue by jonathanpeppers** [Clancey/FlyoutNavigation#17]
Let's say you have a menu item in the left that has nested items, such as:

```
       flyout.NavigationRoot = new RootElement(string.Empty)
        {
            new Section()
            {
                new ImageStringElement("Book", NavigateToBook, Theme.PanelIconBook),
                new ImageStringElement("Activities", NavigateToActivities, Theme.PanelIconActivity),
                new ImageStringElement("Notes", NavigateToNotes, Theme.PanelIconPencil),
                new ImageStringElement("Bookmarks", NavigateToBookmarks, Theme.PanelIconBookmark),
                new ImageStringElement("Presentations", NavigateToPresentations, Theme.PanelIconPresentation),
                new RootElement("Settings")
                {
                    new Section()
                    {
                        new StringElement("Change Password"),
                        new StringElement("Log Out"),
                    }
                },
            },
        };
```

The bottom "Settings" item appears modally because MonoTouch.Dialog can't find a valid NavigationController to push to. This isn't proper iOS navigation for nesting elements, it looks kind of strange.

Making FlyoutNavigationController a UINavigationController might be a way to support this, but I'll leave the implementation details up to you.

**Comment by harshtheone22** [comment]
var frame = mainView.Frame;  This code throws nullReferanceException Error while i run the solution. 
My flyout menu had the same problem, when i clicks on menu button once after login! it doesn't allow me to navigate.  I have used your given code above. but now its throws "nullReferanceException".

#73 FlyoutNavigationController.cs  File

public override void ViewWillAppear(bool animated)
		{
			CGRect navFrame = navigation.View.Frame;
			navFrame.Width = menuWidth;
			if (Position == FlyOutNavigationPosition.Right)
				navFrame.X = mainView.Frame.Width - menuWidth;
			navFrame.Location = CGPoint.Empty;
			navigation.View.Frame = navFrame;
			View.BackgroundColor = NavigationTableView.BackgroundColor;

			var frame = mainView.Frame;

			setViewSize ();
			SetLocation (frame);
			navigation.OnSelection += NavigationItemSelected;
			base.ViewWillAppear(animated);
		} 



MainController.cs  File

public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Create the flyout view controller, make it large,
			// and add it as a subview:
			navigation = new FlyoutNavigationController ();
			navigation.Position = FlyOutNavigationPosition.Left;
			navigation.View.Frame = UIScreen.MainScreen.Bounds;
			View.AddSubview (navigation.View);
			this.AddChildViewController (navigation);


			navigation = new FlyoutNavigationController {
				NavigationRoot = new RootElement ("Access") {
					new Section ("Pages") {
						new StringElement ("Login"),
						new StringElement ("Home Page"),
						new StringElement ("Search"),
					}
				},
				//Supply viewcontroller
				ViewControllers = new [] {
					new UINavigationController (new MyStoryboardViewController ()),
					new UINavigationController (new HomePageViewController ()),
					new UINavigationController (new SearchPageViewController ()),
				},


			};


What should be the changes ??

**Comment by jonathanpeppers** [comment]
This is so old, it should be closed.
