### ISSUE TITLE
Flyout navigation RowClick

### ISSUE THREAD

**Issue by psmds** [Clancey/FlyoutNavigation#68]
Flyout navigation has been working fine.But after I converted my code into unified. I got a problem in my app which contain login screen. after we login, the flyout navigation table view click(row click) is not working(unable to move next view controller) but if I went to new presentviewcontroller(i.e card.io) and come back its working fine.

**Comment by Clancey** [comment]
I am using this in unified in 3 different apps without any issue. Without seeing code it's impossible to tell you what you are doing wrong.

**Comment by psmds** [comment]
Hi Clancey,

Please find the below code.

I'm calling homeController from *LoginController*
using below code
Home homeObject=new Home();
this.NavigationController.PushViewController(this.homeObject,true);

*Home*

   FlyoutNavigationController  myflyout = new FlyoutNavigationController ();
    UIView background = new UIView ();
   background.ContentMode = UIViewContentMode.ScaleAspectFill;
   background.Add (bg);

     UIImageView bg = new UIImageView (new CGRect (0f, 0f, 
View.Bounds.Width, View.Bounds.Height));
     bg.Image = imgBackground;
     bg.ContentMode = UIViewContentMode.ScaleAspectFill;

     myflyout.NavigationTableView.BackgroundView = bg;
     myflyout.NavigationTableView.RowHeight = 44;
     myflyout.NavigationTableView.SectionIndexBackgroundColor = 
UIColor.Clear;
     myflyout.NavigationTableView.SectionIndexColor = UIColor.White;

     myflyout.NavigationTableView.SeparatorStyle = 
UITableViewCellSeparatorStyle.None;
     myflyout.NavigationTableView.SectionHeaderHeight = 20;
     myflyout.NavigationTableView.Frame = new CGRect (0f, 250f, 
View.Bounds.Width, View.Bounds.Height);
     myflyout.NavigationTableView.TintColor = new UIColor (1, 1, 1, 1);


     myflyout.NavigationRoot = new RootElement ("Home") {
      new Section ()
      {
       GetMenuItem ("Single Item Payment", imgSinglePay),
       GetMenuItem ("Multi-items Payment", imgMultiPay),
       GetMenuItem ("Shopping Cart Setup", imgCartSetup),
       GetMenuItem ("Tax and Tips Setup", imgBillSettings),
       GetMenuItem ("History", imgHistory),
       GetMenuItem ("BitCoin History", imgHistory),
       GetMenuItem ("Reports", imgReports),
       GetMenuItem ("Settings", imgSettings),
       GetMenuItem("Business Logo",imgUpload),
       GetMenuItem ("Change Password", imgChangePassword),
       GetMenuItem ("Help", imgHelp),
       GetMenuItem ("Support", imgSupport),
       GetMenuItem ("Donate to charity", imgDonate),
       GetMenuItem ("Logout", imgLogout)
      }
     };


     myflyout.ViewControllers = new []
     {
      new MainPage (SellerToken, this, mailid, userid, flyout)as 
UIViewController,

      new CartView (SellerToken, this, mailid, userid, flyout)as 
UIViewController,
      new AddCategory (flyout)as UIViewController,
      new BuildSettings (flyout)as UIViewController,

      new History (username, password, this, mailid, CustomerID, 
userorgid, flyout)as UIViewController,
      new Bitcoinhistory (username, password, this, mailid, CustomerID, 
userorgid, flyout)as UIViewController,
      new SalesProductChart (flyout)as UIViewController,
      new Debit_Settings (userid, username, password, phoneno, mailid, 
dob, SellerToken, this, flyout)as UIViewController,
      new UploadMerchantLogo (flyout)as UIViewController,
      new Changepassword (username, this, flyout)as UIViewController,
      new Debit_table_help (this, flyout)as UIViewController,
      new Support (userid, mailid, phoneno, this, flyout),

      new DonateCharity(mailid,flyout)as UIViewController,

      new UINavigationController (new Loginpage (this, "logout"))
     };

     View.AddSubview (myflyout.View);
     View.Add (statusview);


While the First time if I go from  login to Home Controller the row 
click is not working(Sliding menu event) but if went to other view 
controller i.e. present viewcontroller from *MainPage* and come back its 
working fine.


Please help me to solve this.

Thanks & Regards,
DineshKumar
