### ISSUE TITLE
Menu item click intercept and set tabbarcontroller's selected tab index

### ISSUE THREAD

**Issue by imfromMO** [Clancey/FlyoutNavigation#71]
I have a flyout navigation with 3 menu items and 3 view controllers.
The 1st view controller is a tabbarcontroller.
I want to set tabbarcontroller's selected tabindex to 0 when the 1st menu item clicked.
Is it possible?

**Comment by imfromMO** [comment]
Is there any way to intercept ToggleMenu()?

**Comment by Clancey** [comment]
There are events you can tie into. If you want intercept, you will need to fork and modify the source.

**Comment by imfromMO** [comment]
I am using Flyout Navigation Xamarin component. What I need is only setting tabbarcontroller's selected tabindex(it could be selected to other index) to 0 when 1st menu item is clicked. Is it impossible with component?
