### ISSUE TITLE
Get current node

### ISSUE THREAD

**Issue by mohsad06** [Clancey/FlyoutNavigation#72]
Hi,

thanks for this great component.
quick question, how can I get the menu title for the current  viewcontroller that I'm in?

for example:

string[] Headers = {
			"Contact Us",
			"Dashboard",
            "Money Transfer",
		};

navigation.NavigationRoot = new RootElement("Menu") {
				new Section ("Menu") {
					from page in Headers
						select new StringElement (page) as Element
				}
			};

and in Dashboard ViewController I wanna get this node text as "Dashboard"

**Comment by Clancey** [comment]
Sure. Use the SelectedIndexChanged action or just SelectedIndex and grab the right one from your array.

**Comment by mohsad06** [comment]
Thanks man, that solved my problem, your component is great.
