### ISSUE TITLE
Pushing new view UIViewController shows side menu in background

### ISSUE THREAD

**Issue by egfconnor** [Clancey/FlyoutNavigation#73]
If I push a new UIViewController I can see the side navigation in the background if it's just a blank UIViewController with no view set. Setting a background color on the new UIViewController such as white/black,etc. will fix it of course.

Strangely if I open the side navigation and select an item and then go back to the previous controller and push a controller the exact same way it has a white background like expected and I can't reproduce it at all after that and an app reload is required.

**Comment by Clancey** [comment]
This isnt really a bug. View controllers are transparent by default.  This allows you to do unique effects.  Because of this, the content view you added is empty until you add content or a background color.

**Comment by egfconnor** [comment]
Gotcha. Thanks for the info!
