### ISSUE TITLE
Fix for ViewWillAppear not firing in some cases

### ISSUE THREAD

**Issue by ianvink** [Clancey/FlyoutNavigation#74]
This is probably a hack fix below, but in my case when   ViewWillAppear does not fire  I use it to ensure it does.

(I use FlyoutNavigation.cs in the AppDelegate)

      public override void ViewWillAppear (bool animated)
      {
         DoSetup ();
         base.ViewWillAppear (animated);
      }

      public void DoSetup ()
      {

         if (!hasSetup) {
            hasSetup = true;
            CGRect navFrame = navigation.View.Frame;
            navFrame.Width = menuWidth;
            if (Position == FlyOutNavigationPosition.Right)
               navFrame.X = mainView.Frame.Width - menuWidth;
            navFrame.Location = CGPoint.Empty;
            navigation.View.Frame = navFrame;
            View.BackgroundColor = NavigationTableView.BackgroundColor;
            var frame = mainView.Frame;
            setViewSize ();
            SetLocation (frame);
            navigation.OnSelection += NavigationItemSelected;
         }
      }

      public override void ViewDidAppear (bool animated)
      {
         base.ViewDidAppear (animated);
         DoSetup ();
         var frame = mainView.Frame;
         setViewSize ();
         SetLocation (frame);
      }

**Comment by Clancey** [comment]
When are you seeing it not fire?  Is it nested inside another ViewController?

**Comment by ianvink** [comment]
Yes, I have a Class that inherits from FlyoutNavigation.cs

**Comment by ianvink** [comment]
I probably missed calling base somewhere, but for now I'm good.

**Comment by Clancey** [comment]
Subclassing shouldn't cause it not to fire. However if you have
 var parent = new UIViewController();
var menu = new FlyoutNavigation();
parent.View.Add(menu.View);

That could easily cause it. You need to add the Child to the parent with
parent.AddChildviewcontroller(menu);

**Comment by ianvink** [comment]
Strange that it is happening now. I have it in several dozen published apps (wonderful by the way!). Xamarin may have changed some internals.

**Comment by Clancey** [comment]
Any way you can create a small sample showing the issue? I am curious.

**Comment by ianvink** [comment]
i'll see what I can do. I noticed my fix doesn't work if a modal advert if
pushed after the screen loads so these is something there.
