### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by DeveloperZone1** [Clancey/FlyoutNavigation#76]
After importing your sample,it refuses to build.
the error is:The compiler seems to have crashed.Building: FlyOutNavigationSample-Classic (Debug|iPhoneSimulator)
Performing main compilation...
/Library/Frameworks/Mono.framework/Versions/3.12.1/bin/mcs /noconfig "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/mscorlib.dll" -nostdlib "/out:/Users/rachealmanda/Desktop/BAckup\/flyoutnavigation-1.5.1/samples/FlyoutNavigationSample-Classic/FlyoutNavigationSample/bin/classic/iPhoneSimulator/Debug/Sample.exe" "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/System.dll" "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/System.Xml.dll" "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/System.Core.dll" "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/monotouch.dll" "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/MonoTouch.Dialog-1.dll" "/r:/Users/rachealmanda/Desktop/BAckup\/flyoutnavigation-1.5.1/lib/ios/FlyoutNavigation.dll" "/r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/System.Core.dll" /nologo /warn:4 /debug:full /optimize- /codepage:utf8 "/define:DEBUG"  "/define:__MOBILE__"  "/define:__IOS__"  /t:exe 
Build complete -- 1 error, 0 warnings

**Comment by Clancey** [comment]
Did you mean to add the Unified sample?
