### ISSUE TITLE
How to Add Image and Text at The top of the menu?

### ISSUE THREAD

**Issue by Tazer2k8** [Clancey/FlyoutNavigation#78]
i wanted to add a image at the top of the menu but i cant figure out how to do it

Like this video: https://www.youtube.com/watch?v=66gIW6Z18jA but right at the top instead

I've tried doing this:

public override void ViewDidLoad ()
{
    base.ViewDidLoad ();
    var navigation = new FlyoutNavigationController {
        // Create the navigation menu
        NavigationRoot = new RootElement ("Navigation") {
MonkeyImage.Image = UIImage.FromBundle ("PurpleMonkey"); //THIS IS WHAT I TRIED ADDING HERE BUT DOES NOT WORK
            new Section ("Pages") {
                new StringElement ("Animals"),
                new StringElement ("Vegetables"),
                new StringElement ("Minerals"),
            }
        },
        // Supply view controllers corresponding to menu items:
        ViewControllers = new [] {
            new UIViewController { View = new UILabel { Text = "Animals (drag right)" } },
            new UIViewController { View = new UILabel { Text = "Vegetables (drag right)" } },
            new UIViewController { View = new UILabel { Text = "Minerals (drag right)" } },
        },
    };

How would i be able to do this?
Thanks

**Comment by Clancey** [comment]
I am not really sure what you are trying to do , but you do not even show the scope of MonkeyImage or what you do with it after you assign he image to it.

**Comment by Tazer2k8** [comment]
Hi Thanks for the Reply here is image of what i kind of want to do 

http://www.theunwired.net/media/news/twitter_android_beta_v5_slideout_menu.jpg

if you look at the twitter image on the top left hand what i want to do something like that but with a username beside it 

another image to hopefully make it a bit more clear

http://t2.gstatic.com/images?q=tbn:ANd9GcRZ19sFUIKCbSxDFPtmsGCTV6JA6U66BNE3wYTz2gK18FeGaBrLIw

**Comment by Clancey** [comment]
The entire menu is built using https://github.com/migueldeicaza/MonoTouch.Dialog

You can use any of the cells or documentation from there to make this work.

**Comment by Tazer2k8** [comment]
OK Thanks for the Help, hopefully I get this working!.

**Comment by Tazer2k8** [comment]
Hey I got the Menu with the Image working but getting into a bit of trouble adding the ToggleMenu to a New Story Board  this is what i am using to get it to display but when i click it, it says Object reference not set to an instance of an object here is what I am doing public 


 FlyoutNavigationController Navigation { get; set; }     
 public MyStoryboardViewController (IntPtr handle) : base (handle)
    {
    }


      base.ViewDidLoad();
        NavigationItem.LeftBarButtonItem = new UIBarButtonItem(UIBarButtonSystemItem.Action, delegate
        {
            navigation.ToggleMenu();
        });
