### ISSUE TITLE
Enable change color of shadow layer 

### ISSUE THREAD

**Issue by trantiendat** [Clancey/FlyoutNavigation#82]
In file : master/FlyoutNavigation/FlyoutNavigationController.cs

I want to enable changing shadow color when dragging content view (it has width that is 5 unit).
I want to change width and color of it.
Now it has width : 5 unit and Black color

Because i use white background in NavigationTableView, so shadow Black is bad idea for my case.

**Comment by Clancey** [comment]
Grab the source, there is nothing stopping you from modifying the shadow values.
