### ISSUE TITLE
How do I change the menu items 

### ISSUE THREAD

**Issue by iunknown21** [Clancey/FlyoutNavigation#83]
Hello, sorry for such a newbie question.  

I've created the Flyout but then later in my application, it's possible to rename one of the views 'Titles'.
Is there a way to 'Rename' the menu names?

I've tried searching thru navigation.NavigationRoot[0].Elements, finding the one I want and changing the Caption, but that doesn't appear to work.

Can you point me in the right direction?

thanks

**Comment by Clancey** [comment]
The navigation is powered by MT.D.  If you want it to update you may have to tell it to reload the row or the tableview after you update the caption.
