### ISSUE TITLE
Close Flyout on screen tap?

### ISSUE THREAD

**Issue by stoberov** [Clancey/FlyoutNavigation#85]
Hello,
Thank you for an awesome FlyoutNavigation! 
One thing I could not solve though - is it possible (how?) for the Flyout to close itself when user taps somewhere else on the screen? Similar to, say, the default flyout/swipe menus in Android apps like Gmail.

**Comment by Clancey** [comment]
Good already exists. The is a property ShpuldStayOpen.

**Comment by Clancey** [comment]
This already exists. The is a property ShouldStayOpen.
