### ISSUE TITLE
Selecting a UIViewElement highlights the row

### ISSUE THREAD

**Issue by FilledStacks** [Clancey/FlyoutNavigation#86]
Hi Clancey,

Awesome component. Works really well, I'm just trying to figure out how to disable table view selection for the NavigationTableView. 

I have tried to set the IUITableViewDelegate and override the ShouldHighlightRow function but it didn't use the delegate I set.

I have also set AllowsSelection = false and it still didn't fix it. Do you have a method that I can use to get this functionality or does it not exist yet.

Regards,
Dane Mackier

**Comment by Clancey** [comment]
The simplest way is to handle this at the element level: https://github.com/migueldeicaza/MonoTouch.Dialog/blob/master/MonoTouch.Dialog/Elements.cs#L762-L767
